# Generated by Django 2.1.4 on 2018-12-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area2076', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/avatars/default.jpg', null=True, upload_to='static/avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_expire',
            field=models.DateField(null=True, verbose_name='date expire'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(null=True, verbose_name='date joined'),
        ),
    ]
