# Generated by Django 2.1.4 on 2019-01-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area2076', '0002_auto_20190105_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='contact'),
        ),
    ]
